[package]
name = "pulse"
description = "Pulse analysis engine: separation-logic-based memory safety checker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sil = { path = "../sil" }
absint = { path = "../absint" }
analyses = { path = "../analyses" }
config = { path = "../config" }
diagnostics = { path = "../diagnostics" }
serde = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
num-rational = { version = "0.4", features = ["serde"] }
num-traits = { workspace = true }
num-bigint = { workspace = true }
rustc-hash = "2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
test-harness = { path = "../test-harness" }
textual = { path = "../textual" }
ondemand = { path = "../ondemand" }
serde_json = "1"
